_BASE_: "../Base-bagtricks.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
  HEADS:
    POOL_LAYER: gempool
  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("VeRiWild", "VeRi",)
  # TESTS: ("LargeVeRiWild", "CarlaVehicle",)
  TESTS: ("CarlaVehicle",)

SOLVER:
  IMS_PER_BATCH: 128
  MAX_ITER: 80
  STEPS: [30, 50]
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

OUTPUT_DIR: "logs/veriwild/bagtricks_R50-ibn_4gpu"
